### ISSUE TITLE
Migrating from Fabric to Firebase

### ISSUE THREAD

**Issue by ssakhavi** [VMadalin/android-modular-architecture#2]
## Description

I wanted to request that you migrate your code from Fabric to Firebase. 

## Basic Information

-   Device type: Android
-   OS version:
-   App version:

**Comment by anticafe** [comment]
It should be [Firebase App Distribution](https://firebase.google.com/docs/app-distribution).

**Comment by Eanam** [comment]
Hi，I am new in the modular thing. When I try this tutorial，I fail at the step of setting the fabric (or firebase). So I want to ask if there has been any progress in the issue #21
