### ISSUE TITLE
Please update project to Firebase Crashlytics

### ISSUE THREAD

**Issue by mohdaquib** [VMadalin/android-modular-architecture#21]
Hi,
Please update code for firebase crashlytics code as fabric moved to firebase.

**Comment by VMadalin** [comment]
Hi mohdaquib. First of all thanks for your issue but seems like it's duplicated one https://github.com/VMadalin/android-modular-architecture/issues/2 . In order to maintain them clean, I will close it as a duplicate. Please any suggestions regard this address it on another issue.
