### ISSUE TITLE
Material Theming Issues in Modules

### ISSUE THREAD

**Issue by zakayothuku** [VMadalin/android-modular-architecture#22]
## Material Theming Issues in Modules

After adding Material theming, the dynamic libraries don't pick the custom theme.

## Details

Add
```
theme.xml
type.xml
shape.xml
```

Reference Custom Theme in theme.xml in one of the module.
Rebuild and run the app.
Theme doesn't not reflect.

**Comment by VMadalin** [comment]
Hi @zakayothuku. First of all, thanks for your ticket. I'm not sure what are you trying to do. In the project are already integrated the material library and the styles defined on the `:app` [module](https://github.com/VMadalin/android-modular-architecture/blob/master/app/src/main/res/values/styles.xml) are used on the different features as you can verify [here](https://github.com/VMadalin/android-modular-architecture/blob/master/features/characters_list/src/main/res/layout/list_item_character.xml#L52) 

Can you please add more details on what are trying?
