### ISSUE TITLE
Could not find com.vanniktech:gradle-android-junit-jacoco-plugin:0.16.0-SNAPSHOT.

### ISSUE THREAD

**Issue by faiz786** [VMadalin/android-modular-architecture#24]
Could not find com.vanniktech:gradle-android-junit-jacoco-plugin:0.16.0-SNAPSHOT.

I am getting this issue after building the application i am new to kotlin can anyone help me solving this issue

**Comment by VMadalin** [comment]
Hi @faiz786. First of all thanks for your ticket. The `master` branch is already updated with the version fixed, you can check that [here](https://github.com/VMadalin/android-modular-architecture/blob/9f9e1445a17384e460b882a29b8ae1b7bd9dd1c9/buildSrc/build.gradle.kts#L42). Basically what happens is that they release the `0.16.0` and the Snapshot is no longer available.

Can you please pull the latest changes on `master` and let me know if you still having problem with the version. Thank you in advance
