### ISSUE TITLE
[TODO] Outdated dependencies.

### ISSUE THREAD

**Issue by ziSo12** [VMadalin/android-modular-architecture#26]
## Description

The project's dependencies, e.g. AGP,  seem to be outdated. Any plans on updating these?

**Comment by VMadalin** [comment]
First of all thank @ziSo12 for your ticket, definitely there was more than a year without updating the dependencies and unfortunately I didn't have the time until now to make these changes. That required several changes on the code to adapt to breaking changes for different libraries
