### ISSUE TITLE
Passing NavController to ViewModel issue

### ISSUE THREAD

**Issue by hulkdx** [VMadalin/android-modular-architecture#32]
Passing NavController to ViewModel is probably a wrong approach in here: 
https://github.com/VMadalin/android-modular-architecture/blob/master/features/home/src/main/kotlin/com/vmadalin/dynamicfeatures/home/ui/HomeViewModel.kt#L43
My opinion is this and the listener should be exists in the Fragment and viewModel when it is needed

**Comment by VMadalin** [comment]
First of all, thank you @hulkdx for your issue. Definitely is something that now I have a different approach in mind. One is that you are commented, moving the `add/removeOnDestinationChangedListener` directly to the `Fragment` or the best one is to create a specific module for the `navigation` responsible for the app navigation. 

I already created a ticket regarding `Improve navigation system` [here](https://github.com/VMadalin/android-modular-architecture/projects/1#card-30052290)
